### ISSUE TITLE
What version of ROS?

### ISSUE THREAD

**Issue by czadikem** [morxa/rosfed#10]
This is a very cool project but I am wondering does this install ROS1 or ROS2?  If it doesn't install ROS 2 do you know how I can get it to install ROS 2?

**Comment by morxa** [comment]
This is ROS1 (ROS Noetic to be exact). There have been some attempts to also support ROS2, but so far there are no ROS2 packages yet. Migrating to ROS2 is not trivial because the build system has changed (although it should be doable with some effort).

We have plans to eventually add support for ROS2, but I can't provide a timeframe.

**Comment by morxa** [comment]
@TarikViehmann has been working  on ROS2, you can test it here: https://copr.fedorainfracloud.org/coprs/tavie/ros2/
